[package]
name = "graph_iter"
version = "0.1.0"
authors = ["Yichuan Shen <shen.yichuan@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
